# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 1000
  connectTimeout: 1000
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 123.126.105.114:22122
    - 123.126.105.115:22122

spring.jmx.enabled: false